#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150px"
# logo text will only show when logo is missing.
logo_text = "Atoms of Us"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "Vanlife ğŸš | Travel ğŸï¸ | Hiking ğŸ¥¾ | Plant-Based ğŸŒ¿ | Environmentalism â™»ï¸ğŸŒ"
author = "AOU"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own
# contact info
# address = "Somewhere in a van"
# mobile = "+211234565523"
# email = "info@email.com"
# contact form action
contact_form_action = "https://formspree.io/f/xyyvearb" # contact form works with https://formspree.io
# search
search = true

# featured post title
featured_post_title = "Featured Posts"
recent_post_title = "Recent Posts"
mainSections = ["blog"]
# about widget content
about_widget_content = "â€œThe fact remains that man has unprecedented control over the world and everything in it. And so, whether he likes it or not, what happens next is very largely up to him.â€ - David Attenborough (From 'Life on Earth' 1979)"
# footer content
footer_content = "Copyright Â© 2022 Atoms of Us <br/> Find an issue with the page? Let us know on [Github](https://github.com/kmalloy24/AOU-Blog/)!"
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/) <br/> Powered by [Hugo](https://gohugo.io/) & [Github Pages](https://pages.github.com/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "We are Chan & Kyle,"
image = "images/banner.webp"
background_image = "/images/banner-bg-shape.svg"
content = "& these are the atoms of us: <br/> Vanlife ğŸš | Travel ğŸï¸ | Hiking ğŸ¥¾ | Plant-Based ğŸŒ¿ | Environmentalism â™»ï¸ğŸŒ"
button_label = "Our Story"
button_link = "about/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "about", "recent-post"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://instagram.com/atoms_of_us"

[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/atomsofus"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/atomsofus"

[[social]]
title = "pinterest"
icon = "fab fa-pinterest" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.pinterest.com/atomsofus/"

[[social]]
title = "youtube"
icon = "fab fa-youtube" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.youtube.com/channel/UC68ue2_WrPT9ELstWcReSkg"